import { useEffect, useState } from 'react';
import {
  AlertCircle, CheckCircle, Clock, TrendingUp, TrendingDown,
  Calendar, Building2, CreditCard, Hash, Shield,
  FileText, Download, Loader2, AlertTriangle, RefreshCw
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { getRecentAlertDetails } from '@/lib/api';

interface AlertDetail {
  id: string;
  message: string;
  status: 'Real' | 'Fake' | 'Pending';
  date: string;
  timestamp: string;
  bank: string;
  accountNumber: string;
  fullAccountNumber: string;
  amount: string;
  type: 'Credit' | 'Debit';
  transactionId: string;
  reference: string;
  balance: string;
  description: string;
  verificationMethod: string;
  confidence: number;
  warnings: string[];
}

export default function AlertDetails() {
  const [alert, setAlert] = useState<AlertDetail | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState('');

  const fetchAlertDetails = async () => {
    setIsLoading(true);
    setError('');
    try {
      const data = await getRecentAlertDetails();
      setAlert(data);
    } catch (err) {
      console.error('Failed to fetch alert details:', err);
      setError('Failed to load alert details');
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    fetchAlertDetails();

    // Refresh when a new alert is detected
    const handleAlertDetected = () => {
      fetchAlertDetails();
    };
    window.addEventListener('alert-detected', handleAlertDetected);
    return () => {
      window.removeEventListener('alert-detected', handleAlertDetected);
    };
  }, []);

  const getStatusConfig = (status: AlertDetail['status']) => {
    switch (status) {
      case 'Real':
        return {
          color: 'bg-green-100 text-green-700 border-green-200',
          bgColor: 'bg-green-50',
          icon: CheckCircle,
          iconColor: 'text-green-600',
          message: 'This alert has been verified as authentic'
        };
      case 'Fake':
        return {
          color: 'bg-red-100 text-red-700 border-red-200',
          bgColor: 'bg-red-50',
          icon: AlertCircle,
          iconColor: 'text-red-600',
          message: 'This alert appears to be fraudulent'
        };
      case 'Pending':
        return {
          color: 'bg-yellow-100 text-yellow-700 border-yellow-200',
          bgColor: 'bg-yellow-50',
          icon: Clock,
          iconColor: 'text-yellow-600',
          message: 'Verification in progress'
        };
      default:
        return {
          color: 'bg-slate-100 text-slate-700 border-slate-200',
          bgColor: 'bg-slate-50',
          icon: Clock,
          iconColor: 'text-slate-600',
          message: 'Status unknown'
        };
    }
  };

  const handleDownloadProof = () => {
    if (!alert) return;

    const statusConfig = getStatusConfig(alert.status);

    // Build a text-based proof document
    const proofContent = `
═══════════════════════════════════════════════════════
           ALERT VERIFICATION PROOF
           FakeBankAlert Detection System
═══════════════════════════════════════════════════════

Document ID:        PROOF-${alert.id}
Generated:          ${new Date().toLocaleString('en-US', {
      dateStyle: 'full',
      timeStyle: 'long'
    })}

───────────────────────────────────────────────────────
                  VERIFICATION RESULT
───────────────────────────────────────────────────────

Status:             ${alert.status.toUpperCase()}
Confidence:         ${alert.confidence}%
Assessment:         ${statusConfig.message}
Verification:       ${alert.verificationMethod}

───────────────────────────────────────────────────────
                 TRANSACTION DETAILS
───────────────────────────────────────────────────────

Alert Message:      ${alert.message}
Type:               ${alert.type}
Amount:             ${alert.amount}
Bank:               ${alert.bank}
Account Number:     ${alert.fullAccountNumber} (${alert.accountNumber})
Balance After:      ${alert.balance}
Transaction ID:     ${alert.transactionId}
Reference:          ${alert.reference}
Date:               ${alert.date}
Time:               ${alert.timestamp}

───────────────────────────────────────────────────────
                    DESCRIPTION
───────────────────────────────────────────────────────

${alert.description}

${alert.warnings && alert.warnings.length > 0 ? `───────────────────────────────────────────────────────
                     WARNINGS
───────────────────────────────────────────────────────

${alert.warnings.map((w, i) => `${i + 1}. ${w}`).join('\n')}
` : ''}
═══════════════════════════════════════════════════════
              DISCLAIMER & LEGAL NOTICE
═══════════════════════════════════════════════════════

This document is generated by the FakeBankAlert
Detection System and is intended for informational
purposes only. The verification is based on AI
analysis and rule-based pattern detection.

This proof was generated at:
${new Date().toISOString()}

Alert ID: ${alert.id}
═══════════════════════════════════════════════════════
`;

    // Create and download the file
    const blob = new Blob([proofContent], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `AlertProof_${alert.id}_${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  // Loading state
  if (isLoading) {
    return (
      <div className="bg-white rounded-xl border border-slate-200 p-6 shadow-sm">
        <div className="flex items-center gap-3 mb-4">
          <div className="bg-blue-50 p-2 rounded-lg">
            <FileText className="w-5 h-5 text-blue-600" />
          </div>
          <h2 className="text-xl font-bold text-slate-900">Latest Alert Details</h2>
        </div>
        <div className="flex items-center justify-center py-12">
          <Loader2 className="w-6 h-6 text-blue-600 animate-spin mr-2" />
          <span className="text-sm text-slate-500">Loading alert details...</span>
        </div>
      </div>
    );
  }

  // Error state
  if (error) {
    return (
      <div className="bg-white rounded-xl border border-slate-200 p-6 shadow-sm">
        <div className="flex items-center gap-3 mb-4">
          <div className="bg-blue-50 p-2 rounded-lg">
            <FileText className="w-5 h-5 text-blue-600" />
          </div>
          <h2 className="text-xl font-bold text-slate-900">Latest Alert Details</h2>
        </div>
        <div className="flex flex-col items-center justify-center py-8 text-center">
          <AlertTriangle className="w-8 h-8 text-red-400 mb-2" />
          <p className="text-sm text-red-600 mb-3">{error}</p>
          <Button onClick={fetchAlertDetails} variant="outline" size="sm">
            <RefreshCw className="w-4 h-4 mr-2" />
            Retry
          </Button>
        </div>
      </div>
    );
  }

  // No alert found
  if (!alert) {
    return (
      <div className="bg-white rounded-xl border border-slate-200 p-6 shadow-sm">
        <div className="flex items-center gap-3 mb-4">
          <div className="bg-blue-50 p-2 rounded-lg">
            <FileText className="w-5 h-5 text-blue-600" />
          </div>
          <h2 className="text-xl font-bold text-slate-900">Latest Alert Details</h2>
        </div>
        <div className="flex flex-col items-center justify-center py-8 text-center">
          <div className="bg-slate-100 p-4 rounded-full mb-3">
            <FileText className="w-8 h-8 text-slate-400" />
          </div>
          <p className="text-sm text-slate-600 font-medium">No alerts yet</p>
          <p className="text-xs text-slate-500 mt-1">Create or detect an alert to see details here</p>
        </div>
      </div>
    );
  }

  const statusConfig = getStatusConfig(alert.status);
  const StatusIcon = statusConfig.icon;

  return (
    <div className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden">
      {/* Header */}
      <div className={`p-5 border-b ${statusConfig.bgColor}`}>
        <div className="flex items-center gap-3 mb-3">
          <div className="bg-blue-50 p-2 rounded-lg">
            <FileText className="w-5 h-5 text-blue-600" />
          </div>
          <h2 className="text-lg font-bold text-slate-900">Latest Alert Details</h2>
        </div>

        <div className="flex items-start gap-3">
          {/* Transaction Icon */}
          <div className={`p-2.5 rounded-xl ${alert.type === 'Credit' ? 'bg-green-100' : 'bg-red-100'
            }`}>
            {alert.type === 'Credit' ? (
              <TrendingUp className="w-6 h-6 text-green-600" />
            ) : (
              <TrendingDown className="w-6 h-6 text-red-600" />
            )}
          </div>

          {/* Alert Info */}
          <div className="flex-1 min-w-0">
            <div className="flex items-start justify-between gap-2">
              <div>
                <h3 className="text-xl font-bold text-slate-900">{alert.amount}</h3>
                <p className="text-sm text-slate-600 truncate">{alert.message}</p>
              </div>
              <span className={`inline-flex items-center gap-1.5 px-2.5 py-1.5 rounded-lg text-xs font-semibold border ${statusConfig.color} whitespace-nowrap`}>
                <StatusIcon className={`w-3.5 h-3.5 ${statusConfig.iconColor}`} />
                {alert.status}
              </span>
            </div>
          </div>
        </div>

        {/* Status Message */}
        <div className={`mt-3 p-2.5 rounded-lg ${statusConfig.color} border`}>
          <p className="text-xs font-medium flex items-center gap-2">
            <Shield className={`w-3.5 h-3.5 ${statusConfig.iconColor}`} />
            {statusConfig.message}
            {alert.confidence > 0 && (
              <span className="ml-auto">Confidence: {alert.confidence}%</span>
            )}
          </p>
        </div>
      </div>

      {/* Transaction Details Grid */}
      <div className="p-5">
        <h4 className="text-sm font-semibold text-slate-700 mb-3">Transaction Details</h4>
        <div className="grid grid-cols-2 gap-2.5">
          {/* Date & Time */}
          <div className="flex items-start gap-2.5 p-3 bg-slate-50 rounded-lg">
            <Calendar className="w-4 h-4 text-slate-400 mt-0.5 flex-shrink-0" />
            <div className="min-w-0">
              <p className="text-xs text-slate-500">Date & Time</p>
              <p className="text-sm font-semibold text-slate-900">{alert.date}</p>
              <p className="text-xs text-slate-600">{alert.timestamp}</p>
            </div>
          </div>

          {/* Bank */}
          <div className="flex items-start gap-2.5 p-3 bg-slate-50 rounded-lg">
            <Building2 className="w-4 h-4 text-slate-400 mt-0.5 flex-shrink-0" />
            <div className="min-w-0">
              <p className="text-xs text-slate-500">Bank</p>
              <p className="text-sm font-semibold text-slate-900 truncate">{alert.bank}</p>
            </div>
          </div>

          {/* Account Number */}
          <div className="flex items-start gap-2.5 p-3 bg-slate-50 rounded-lg">
            <CreditCard className="w-4 h-4 text-slate-400 mt-0.5 flex-shrink-0" />
            <div className="min-w-0">
              <p className="text-xs text-slate-500">Account</p>
              <p className="text-sm font-semibold text-slate-900">{alert.accountNumber}</p>
            </div>
          </div>

          {/* Type */}
          <div className="flex items-start gap-2.5 p-3 bg-slate-50 rounded-lg">
            <Hash className="w-4 h-4 text-slate-400 mt-0.5 flex-shrink-0" />
            <div className="min-w-0">
              <p className="text-xs text-slate-500">Type</p>
              <p className={`text-sm font-semibold ${alert.type === 'Credit' ? 'text-green-600' : 'text-red-600'
                }`}>
                {alert.type}
              </p>
            </div>
          </div>

          {/* Balance */}
          <div className="flex items-start gap-2.5 p-3 bg-slate-50 rounded-lg">
            <TrendingUp className="w-4 h-4 text-slate-400 mt-0.5 flex-shrink-0" />
            <div className="min-w-0">
              <p className="text-xs text-slate-500">Balance</p>
              <p className="text-sm font-semibold text-slate-900">{alert.balance}</p>
            </div>
          </div>

          {/* Transaction ID */}
          <div className="flex items-start gap-2.5 p-3 bg-slate-50 rounded-lg">
            <Hash className="w-4 h-4 text-slate-400 mt-0.5 flex-shrink-0" />
            <div className="min-w-0">
              <p className="text-xs text-slate-500">Transaction ID</p>
              <p className="text-xs font-mono text-slate-900 truncate">{alert.transactionId}</p>
            </div>
          </div>
        </div>

        {/* Description */}
        {alert.description && (
          <div className="mt-3 p-3 bg-slate-50 rounded-lg">
            <p className="text-xs text-slate-500 mb-1">Description</p>
            <p className="text-sm text-slate-900">{alert.description}</p>
          </div>
        )}

        {/* Warnings */}
        {alert.warnings && alert.warnings.length > 0 && (
          <div className="mt-3">
            <p className="text-xs font-semibold text-amber-700 mb-1.5 flex items-center gap-1.5">
              <AlertTriangle className="w-3.5 h-3.5" />
              Warnings ({alert.warnings.length})
            </p>
            <div className="space-y-1">
              {alert.warnings.map((warning, index) => (
                <div key={index} className="flex items-start gap-2 text-xs text-amber-700 bg-amber-50 px-2.5 py-1.5 rounded-md">
                  <span className="text-amber-400 mt-px">•</span>
                  <span>{warning}</span>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Verification Method */}
        <div className="mt-3 p-3 bg-blue-50 border border-blue-100 rounded-lg">
          <div className="flex items-center gap-2">
            <Shield className="w-4 h-4 text-blue-600 flex-shrink-0" />
            <div>
              <p className="text-xs font-semibold text-blue-900">Verification Method</p>
              <p className="text-xs text-blue-700">{alert.verificationMethod}</p>
            </div>
          </div>
        </div>
      </div>

      {/* Action Buttons */}
      <div className="px-5 pb-5">
        <div className="grid grid-cols-2 gap-2">
          <Button
            onClick={handleDownloadProof}
            variant="outline"
            size="sm"
            className="w-full border-slate-300 hover:bg-slate-50 text-sm"
          >
            <Download className="w-4 h-4 mr-1.5" />
            Download Proof
          </Button>
          <Button
            onClick={fetchAlertDetails}
            variant="outline"
            size="sm"
            className="w-full border-slate-300 hover:bg-slate-50 text-sm"
          >
            <RefreshCw className="w-4 h-4 mr-1.5" />
            Refresh
          </Button>
        </div>
      </div>
    </div>
  );
}